### ISSUE TITLE
raw_content parameter not implemented for document creation with knowledge connectors

### ISSUE THREAD

**Issue by roebius** [googleapis/dialogflow-python-client-v2#101]
Using the _v2beta1_ library, when trying to create a `dialogflow.types.Document` object passing a `raw_content` parameter (instead of a `content_uri` parameter) I get a _'Document' object has no attribute 'raw_content'_ error.

On the other hand, I was able to successfully pass a `content` parameter (preparing to upload local txt files), but it is deprecated and it doesn't work for pdf files (as per the "Supported content" section at [Knowledge Connectors](https://cloud.google.com/dialogflow-enterprise/docs/knowledge-connectors))

Is `raw_content` on the way (or am I missing anything)?
Thanks

**Comment by tseaver** [comment]
Per the [protobuf description of `dialogflow_v2beta1.Document`](https://github.com/googleapis/googleapis/blob/200fbbe59cc7b0077ae525eb5f3d6420c0c53e61/google/cloud/dialogflow/v2beta1/document.proto#L85-L138), the attribute name should be `content`, not `raw_content.
