### ISSUE TITLE
Unable to Run detect_intents_text.py

### ISSUE THREAD

**Issue by yashpatel001** [googleapis/dialogflow-python-client-v2#102]
i am running using 
python detect_intent_texts.py "projectname"  "12345" "good morning"

error:
detect_intent_texts.py: error: argument --project-id is required

help to how to pass projectid
how to get session id

**Comment by emibelli** [comment]
Hi @yashpatel001!

According to the [docs](https://github.com/googleapis/dialogflow-python-client-v2/tree/master/samples#detect-intent-text), the correct usage for detect_intent_texts.py is:

```bash
$ python detect_intent_texts.py

usage: detect_intent_texts.py [-h] --project-id PROJECT_ID
                              [--session-id SESSION_ID]
                              [--language-code LANGUAGE_CODE]
                              texts [texts ...]
```

Hope this helps!

**Comment by sduskis** [comment]
It looks like the question was answered.  @yashpatel001, please reopen if this is still an issue.
