### ISSUE TITLE
How to get action and Parameters with Dialogflow API

### ISSUE THREAD

**Issue by hueiyuanSu** [googleapis/dialogflow-python-client-v2#104]
I want to get information about action and parameters with dialogflow api. like this screenshot.
<img width="759" alt="2018-11-05 6 29 24" src="https://user-images.githubusercontent.com/17706153/47992834-e8793880-e128-11e8-8acc-8f15c7f4d06c.png">

But I do not know how to implement it.

**Comment by crwilcox** [comment]
The documentation for this is https://dialogflow.com/docs/intents/actions-parameters 

This sample, https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dialogflow/cloud-client/detect_intent_texts.py#L34, will show you how to detect an intent, action and parameters are fields on the response. These fields are more interesting if used against a non-default intent.

```
import dialogflow

audio_file_path = "/Users/USERNAME/Downloads/book_a_room.wav"

session_client = dialogflow.SessionsClient()
session = session_client.session_path('MYPROJECT', 'foo-session-id')

audio_encoding = dialogflow.enums.AudioEncoding.AUDIO_ENCODING_LINEAR_16
sample_rate_hertz = 16000
audio_config = dialogflow.types.InputAudioConfig(
        audio_encoding=audio_encoding, language_code=language_code,
        sample_rate_hertz=sample_rate_hertz)

with open(audio_file_path, 'rb') as audio_file:
    input_audio = audio_file.read()

query_input = dialogflow.types.QueryInput(audio_config=audio_config)

response = session_client.detect_intent(
    session=session, query_input=query_input,
    input_audio=input_audio)


response
"""
response_id: "1a0cacb1-6523-43a4-aa23-54092662b6b6"
query_result {
  query_text: "book a room"
  speech_recognition_confidence: 0.9123808145523071
  action: "input.unknown"
  parameters {
  }
  all_required_params_present: true
  fulfillment_text: "I didn\'t get that. Can you repeat?"
  fulfillment_messages {
    text {
      text: "Say that one more time?"
    }
  }
  intent {
    name: "projects/MYPROJECT/agent/intents/6ac374f5-047d-4af7-9411-812fadf5ef2e"
    display_name: "Default Fallback Intent"
    is_fallback: true
  }
  intent_detection_confidence: 1.0
  language_code: "en-us"
}
"""
```

**Comment by abderrahmane8** [comment]
Thanks

**Comment by grayrhinos** [comment]
> The documentation for this is https://dialogflow.com/docs/intents/actions-parameters
> 
> This sample, https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dialogflow/cloud-client/detect_intent_texts.py#L34, will show you how to detect an intent, action and parameters are fields on the response. These fields are more interesting if used against a non-default intent.
> 
> ```
> import dialogflow
> 
> audio_file_path = "/Users/USERNAME/Downloads/book_a_room.wav"
> 
> session_client = dialogflow.SessionsClient()
> session = session_client.session_path('MYPROJECT', 'foo-session-id')
> 
> audio_encoding = dialogflow.enums.AudioEncoding.AUDIO_ENCODING_LINEAR_16
> sample_rate_hertz = 16000
> audio_config = dialogflow.types.InputAudioConfig(
>         audio_encoding=audio_encoding, language_code=language_code,
>         sample_rate_hertz=sample_rate_hertz)
> 
> with open(audio_file_path, 'rb') as audio_file:
>     input_audio = audio_file.read()
> 
> query_input = dialogflow.types.QueryInput(audio_config=audio_config)
> 
> response = session_client.detect_intent(
>     session=session, query_input=query_input,
>     input_audio=input_audio)
> 
> 
> response
> """
> response_id: "1a0cacb1-6523-43a4-aa23-54092662b6b6"
> query_result {
>   query_text: "book a room"
>   speech_recognition_confidence: 0.9123808145523071
>   action: "input.unknown"
>   parameters {
>   }
>   all_required_params_present: true
>   fulfillment_text: "I didn\'t get that. Can you repeat?"
>   fulfillment_messages {
>     text {
>       text: "Say that one more time?"
>     }
>   }
>   intent {
>     name: "projects/MYPROJECT/agent/intents/6ac374f5-047d-4af7-9411-812fadf5ef2e"
>     display_name: "Default Fallback Intent"
>     is_fallback: true
>   }
>   intent_detection_confidence: 1.0
>   language_code: "en-us"
> }
> """
> ```

So I have two REQUIED parameters and I am accessing Dialogflow from my Facebook bot backend. session_client.detect_intent() does not return anything cause the required parameters are  missing. Also I am PROMPS questions to fill the required parameters. How can I handle that from my Facebook backend?
