### ISSUE TITLE
about the relationship about context and session

### ISSUE THREAD

**Issue by hueiyuanSu** [googleapis/dialogflow-python-client-v2#106]
Excuse me.
I hava a problem.
I do not know the relationship about context and session .
Because I want to build context ,like the photo
<img width="806" alt="2018-11-07 6 22 11" src="https://user-images.githubusercontent.com/17706153/48125830-9bc56700-e2ba-11e8-8811-87e8c8275d35.png">
I just see the setting of context. therefore, I want to ask what is session and its means.
thanks.

**Comment by busunkim96** [comment]
https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Sessions

> A session represents an interaction with a user.

https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.Contexts
> A context represents additional information included with user input or with an intent returned by the Dialogflow API. Contexts are helpful for differentiating user input which may be vague or have a different meaning depending on additional details from your application such as user setting and preferences, previous user input, where the user is in your application, geographic location, and so on.


If your questions are not about the python client you will probably get better responses through [Dialogflow support](https://dialogflow.com/support#contact-us).
