### ISSUE TITLE
Request for Quota Tracking

### ISSUE THREAD

**Issue by mattare2** [googleapis/dialogflow-python-client-v2#111]
Is there a way to return the number of API requests, so as not to exceed quota? 

I am tracking this now in my own code, but my estimates seem to be off (resulting in many quota errors)

Thanks!

**Comment by busunkim96** [comment]
Hi @mattare2, 

Unfortunately it's not possible to track that with this library. You can track API requests on the [API Dashbaord](https://console.cloud.google.com/apis/dashboard) or by querying [Stackdriver Monitoring](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-serviceruntime) for the `serviceruntime` metric .
