### ISSUE TITLE
google.api_core.exceptions.ServiceUnavailable: 503 Connect Failed

### ISSUE THREAD

**Issue by deena-philip** [googleapis/dialogflow-python-client-v2#118]
The google.api_core.exceptions.ServiceUnavailable: 503 Connect Failed error occurs when we call the [detect_intent](https://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/api.html#dialogflow_v2.SessionsClient.detect_intent) or [create_context](https://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/api.html#dialogflow_v2.ContextsClient.create_context) methods. 

dialogflow.ContextsClient().create_context(session, context)
  File "/usr/local/lib/python3.7/site-packages/dialogflow_v2/gapic/contexts_client.py", line 405, in create_context
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
    # Permission is hereby granted, free of charge, to any person obtaining a copy
google.api_core.exceptions.ServiceUnavailable: 503 Connect Failed

**Comment by elchory96** [comment]
You must configure the variable GOOGLE_APPLICATION_CREDENTIALS

https://cloud.google.com/docs/authentication/

You must configure it with the .JSON file

**Comment by deena-philip** [comment]
@elchory96 The authentication using json file has already been done.
The 503 error occurs intermittently.

**Comment by deena-philip** [comment]
Using a single instance of a session client object for multiple requests seems to have resolved the issue.

**Comment by soominjung** [comment]
@deena-philip
Did you use multiple instances of a session client before?
It seems like I have only one instance but the same issue happens to me.

**Comment by ognacy** [comment]
it happens to me too, intermittently. we are running a large workload on dialogflow and it just keeps happening. our stuff is running in cloud run, authenticates with system managed keys, and for something like 0.1% of calls it returnes 503 on either detect_intent or create_context. I have not had the time to debug it yet, for now we are just repeating such failed requests.

**Comment by deena-philip** [comment]
@ognacy Yes, we also did the same.
