### ISSUE TITLE
Batch Detect Intent

### ISSUE THREAD

**Issue by joeyism** [googleapis/dialogflow-python-client-v2#121]
I have many things of which I need to detect the intent, and I run into the Dialogflow text limit. 

I looked through the [docs](https://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/api.html#dialogflow_v2.SessionsClient) and couldn't find a way to make multiple intent query per request. 
I was wondering if there is a way for me to do batch `session_client.detect_intent` instead of making a network call every time.

**Comment by nnegrey** [comment]
No, sorry that is not currently supported. For Feature Request, please file on this page: https://cloud.google.com/support/docs/issue-trackers
