### ISSUE TITLE
Update Intent Optional Field is not Optional

### ISSUE THREAD

**Issue by nnegrey** [googleapis/dialogflow-python-client-v2#129]
In the `updateIntent` method, the `language_code` is listed as optional, but if you try to call the library without passing in that argument you get it error that it is required. 

https://github.com/googleapis/dialogflow-python-client-v2/blob/master/dialogflow_v2/gapic/intents_client.py#L518-L547

**Comment by busunkim96** [comment]
`language_code` is described as an optional field in the RPC API Reference as well

https://cloud.google.com/dialogflow/docs/reference/rpc/google.cloud.dialogflow.v2beta1#updateintentrequest

**Comment by czahedi** [comment]
Hi folks,

What's the plan here? Noah and Bu Sun, can you revisit this and all the related Dialogflow Python issues? If there's work to be done I'd love for us to get started on it since these are out of SLO. It's possible a recent regen has fixed this though.

Thanks!

**Comment by nnegrey** [comment]
It appears the v2 (not v2beta1) proto has been fixed with annotations:

Changed here: https://github.com/googleapis/googleapis/commit/b7abb49e0a285829ae2463486e5047eb320791ac#diff-3bd3ac95a9428fb7b5e51caee180b94f

https://github.com/googleapis/googleapis/blob/master/google/cloud/dialogflow/v2/intent.proto#L1015

But library doesn't seem to have those changes: https://github.com/googleapis/dialogflow-python-client-v2/blob/master/dialogflow_v2/gapic/intents_client.py#L544

Issue with the generator or micro-generator?

**Comment by busunkim96** [comment]
@nnegrey The updates aren't merged automatically into the library. Autosynth currently opens a PR when it notices a difference in a regeneration. I think https://github.com/googleapis/dialogflow-python-client-v2/pull/163/files has a change to make `language_code` required.

**Comment by nnegrey** [comment]
That PR is for the KnowledgeBases, where the issue is still on the UpdateIntents call.

**Comment by busunkim96** [comment]
@nnegrey Yep! But any proto changes that happened after that won't appear until that one gets merged. Alternatively you can close that one and wait for a new PR to appear.

**Comment by nnegrey** [comment]
Oh..... now I get it. 

But the new annotations got updated in September from the date, does that mean the one above although from October is maybe older? (sorry confused again)

**Comment by busunkim96** [comment]
Hmm, it does look like there's a mismatch. :sob: I'm going to close the open synth PR to see if we get something new tomorrow. Dialogflow is using the old generator (gapic-generator).

**Comment by nnegrey** [comment]
Looks like an issue with the old generator. :(

**Comment by czahedi** [comment]
Bu Sun please keep us updated on what you find :)

**Comment by czahedi** [comment]
Hey folks, any update here?

**Comment by busunkim96** [comment]
It looks like Dialogflow has not been migrated to use the new proto annotations, so required/optional is determined by the GAPIC config. https://github.com/googleapis/googleapis/blob/2e23b8fbc45f5d9e200572ca662fe1271bcd6760/google/cloud/dialogflow/v2beta1/dialogflow_gapic.yaml#L838 line makes `language_code` required.

Opening a CL now to fix it.

**Comment by czahedi** [comment]
Hey Bu Sun, checking back in. Did that other CL you mentioned go through?

**Comment by busunkim96** [comment]
Closed by #175
