### ISSUE TITLE
How can I take training phrases and responses of Intent?

### ISSUE THREAD

**Issue by alibaraneser** [googleapis/dialogflow-python-client-v2#131]
Hey,

I want to take training phrases and responses of relational intent.

I guess, API only provided intent create, delete process, isn't it?

**Comment by busunkim96** [comment]
Hi @alibaraneser! If your question is about Dialogflow more generally (whether these features are available in the API), you will be able to get a better answer by looking through documentation and asking your question on Stackoverflow.

If your question is about how to do these things with this library specifically, please let us know.

* https://dialogflow.com/docs 
* https://stackoverflow.com/questions/tagged/dialogflow

**Comment by alibaraneser** [comment]
> Hi @alibaraneser! If your question is about Dialogflow more generally (whether these features are available in the API), you will be able to get a better answer by looking through documentation and asking your question on Stackoverflow.
> 
> If your question is about how to do these things with this library specifically, please let us know.
> 
> * https://dialogflow.com/docs
> * https://stackoverflow.com/questions/tagged/dialogflow

Firstly, I'm looking for thing that I want in Samples codes, but cannot find.
But now, I found method inside of Project Files.

**Comment by nnegrey** [comment]
Please see here for the most up to date samples: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/dialogflow/cloud-client
