### ISSUE TITLE
How to use multiple GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by alibaraneser** [googleapis/dialogflow-python-client-v2#132]
I want to use several GOOGLE_APPLICATION_CREDENTIALS in concurrceny. But I can only use one in the environment settings.

Note : using Flask

**Comment by busunkim96** [comment]
Hi @alibaraneser, you can only use one set of credentials via GOOGLE_APPLICATION_CREDENTIALS. I'd recommend granting additional permissions to one of the service account if you're working across projects. 

Let us know if you need more help!
