### ISSUE TITLE
types.QueryParameters doesn't accept payload param. 

### ISSUE THREAD

**Issue by zzart** [googleapis/dialogflow-python-client-v2#139]
#### Environment details

  - OS: linux
  - Python version: 3.7
  - pip version: latest
  - `dialogflow` version: dialogflow==0.6.0

#### Steps to reproduce

  1. 
```
.... code omitted ... 

query_params = dialogflow.types.QueryParameters(payload={"foo": "bar"}) 
response = session_client.detect_intent(
            session=session, 
            query_input=query_input, 
            query_params=query_params,
 )

```
Raises : `ValueError: Protocol message Struct has no "foo" field.` 
From docs: 

>  payload:
 |          Optional. This field can be used to pass custom data into the
 |          webhook associated with the agent. Arbitrary JSON objects are
 |          supported.

Doesn't look like there are supported without explicitly defining sth along these lines and returning it for `query_params`: 

```
def create_context(project_id, session_id, query_params):
    context_short_name = "does_not_matter"
    context_name = "projects/" + project_id + "/agent/sessions/" + session_id + "/contexts/" + context_short_name.lower()
    parameters = dialogflow.types.struct_pb2.Struct()
    parameters.update(query_params)
    context_1 = dialogflow.types.context_pb2.Context(
        name=context_name,
        lifespan_count=2,
        parameters=parameters
    )

    query_params = {"contexts": [context_1]}
    return query_params
``` 
But with a Struct like this how can you pass other params ie. `knowledge_base_names` for  `query_params` ? 
I need to pass both `knowledge_base_names` and `payload`  to `query_params` and cannot find a  way to do so.

**Comment by xronsx** [comment]
Hi, did you find any solution for this?

**Comment by zzart** [comment]
Yeh, I did something along these lines 
```
def create_context(
    query_params: dict, knowledge_base: list
) -> dict:
    parameters = dialogflow.types.struct_pb2.Struct()
    parameters.update(query_params)
    context = dialogflow.types.context_pb2.Context(
        name=context_name, lifespan_count=2, parameters=parameters
    )

    query_params = {"contexts": [context], "knowledge_base_names": knowledge_base}
    return query_params



# then you can do
session_client.detect_intent(
     ....    
        query_params=create_context(
            query_params, knowledge_bases
        ),
    )
```
