### ISSUE TITLE
Is there a way to promote/deploy a version of the agent to an environment (beta feature) via command-line or REST?

### ISSUE THREAD

**Issue by k-root** [googleapis/dialogflow-python-client-v2#141]
I am working with the beta version of Dialogflow which has released "Environments" feature. Currently I have created different environments and published multiple versions of the agent in the environments using the Dialogflow console. Is there a way to publish a version to an environment via command line, REST API, or using npm dialogflow package?

**Comment by nnegrey** [comment]
As of today, I don't think there is. 

You can use it for like detect intent calls and similar, but not uploading new versions of your agent.

https://github.com/googleapis/googleapis/blob/master/google/cloud/dialogflow/v2beta1/session.proto#L55-L72
