### ISSUE TITLE
session entities are not always updated

### ISSUE THREAD

**Issue by mcikosos** [googleapis/dialogflow-python-client-v2#143]
#### Environment details

  - OS:
  - Python version: 3.6
  - pip version: 19.2.3
  - `dialogflow` version:  v0.6.0

#### Steps to reproduce

  1. Setup dialogflow project with some empty entities (5 pieces)
  2. Try to update them using create_session_entity_type() function in a loop (each as different future)
      NOTICE: There is no error during function call and function response is correct
  3. list session entities using REST API

Result: Some time not all entities are created.

Another case:
  1. Setup dialogflow project with some empty entities (5 pieces)
  2. Try to update them using create_session_entity_type() function in a loop 
  3. list session entities using REST API - looks ok
  4. update one of created entities using REST API - with some different value
  5. Try to update them all again using create_session_entity_type() function in a loop (to previous/original value)
  6. list session entities using REST API 

Result: The value is not updated in step 5 - still is set as in step 4

**Comment by mcikosos** [comment]
> Are you calling all of these back to back in quick succession?
Yes

**Comment by mcikosos** [comment]
> On Dialogflow there is some latency when creating or making changes to an agent. It can take a few seconds for the agent to pick up the changes and re-train the agent to handle new user input.

As I wrote I use REST API to check the values and even after a long time they are not there

**Comment by nnegrey** [comment]
Can you share some code or is there a specific example you are looking at?

**Comment by mcikosos** [comment]
> Can you share some code or is there a specific example you are looking at?

It is split in multiply modules so I will cut of essential parts:

`    def create_session_entity_type(self, entity_name, entity_entries):
        name = EntitiesClient.session_entity_type_path(self._google_project_id, self._session, entity_name)
        session_entity_type = SessionEntityType(name=name, entity_override_mode="ENTITY_OVERRIDE_MODE_OVERRIDE",
                                                entities=entity_entries)
        try:
            return self.entity_client().create_session_entity_type(self._session_id, session_entity_type, timeout=self._timeout)
        except Exception as e:
            logging.error(str(e))
            raise ServicesRegistry.DialogflowException("SERVICE_TIMEOUT", "Dialogflow - Entities Client")
`
called from

`def _upload_entity(entities_list, entity_name):
    response = None
    entities_str = entity_name + ": "
    if entities_list:
        entity_entries = []
        for entity in entities_list:
            name = remove_special_characters(entity.get("name", ""))
            if name:
                source = entity.get("source", hc_selector().get_hc_id())
                value = '{{"source":"{}","id":"{}","name":"{}"}}'.format(source, entity.get("id"), name)
                entity_entries.append(EntityType.Entity(value=value, synonyms=[name]))
                entities_str = "{}{}, ".format(entities_str, value)
        try:
            response = dialogflow().create_session_entity_type(entity_name, entity_entries)
            logging.debug(newlines_to_carriage_return(response))
        except Exception as error:
            logging.error("error_msg=%s", str(error))

    logging.info(entities_str)
    return response`

which is called from:

`def _inject_entities(names):
    ret = api().get_info()
    entities = {}
    error = ""

    if ret:
        entities_names = []
        for name in names:
            entities_list=ret.get(name)
            if entities_list:
                entities_names.append(name)
        if entities_names:
            executor = concurrent.futures.ThreadPoolExecutor(len(entities_names))
            upload_results={}
            for name in entities_names:
                upload_results[name] = executor.submit(_upload_entity, ret.get(name), name)
            try:
                for name, res in upload_results.items():
                    entities[name] = res.result()
            except Exception as error:
                error = str(error)

    return entities, ret, error`

**Comment by nnegrey** [comment]
Few questions:

1. Do these EntityTypes already exist as you are using the override mode vs supplement?
2. Is your `EntityType` a kind value of `KIND_MAP`?
3. Is your `self._session_id` created like this?
```
session_path = session_entity_types_client.session_path(
        project_id, session_id)
```

**Comment by mcikosos** [comment]
Ad 1. They exist - with some dummy content - defined in dialogflow console
Ad 2. EntityType - I dont set the entity type - it was created in dialogflow console - when I check exported json:
```
{
  "id": "88cd92cf-37d8-4f26-92fa-1eee8f3c5f62",
  "name": "ProgrammableDevice",
  "isOverridable": true,
  "isEnum": false,
  "isRegexp": false,
  "automatedExpansion": false,
  "allowFuzzyExtraction": false
}
```
 
Ad 3. self._session_id is taken from request session field - so it is full path  - ex:  projects/project-xyz/agent/sessions/a5842290-9952-4ab6-965d-302c0bc70383

**Comment by nnegrey** [comment]
Oh I forgot to ask, about how many session entities are you trying to update?

**Comment by nnegrey** [comment]
```
###### CREATE ######
SessionEntityType created: 

name: "projects/PROJECT_ID/agent/sessions/session1234/entityTypes/test-entity"
entity_override_mode: ENTITY_OVERRIDE_MODE_OVERRIDE
entities {
  value: "look1"
  synonyms: "look1"
}
entities {
  value: "look2"
  synonyms: "look2"
}
entities {
  value: "look3"
  synonyms: "look3"
}

###### LIST ######
SessionEntityTypes for session projects/PROJECT_ID/agent/sessions/session1234:

name: "projects/PROJECT_ID/agent/sessions/session1234/entityTypes/test-entity"
entity_override_mode: ENTITY_OVERRIDE_MODE_OVERRIDE
entities {
  value: "look1"
  synonyms: "look1"
}
entities {
  value: "look2"
  synonyms: "look2"
}
entities {
  value: "look3"
  synonyms: "look3"
}
```

**Comment by nnegrey** [comment]
A scaled down version of what you have above that is working for me. 

```
def create_session_entity_type(client, session_path, entity_type_display_name,
                               project_id, session_id):
    import dialogflow_v2 as dialogflow
    entity_values = ['look1', 'look2', 'look3']
    entity_override_mode = 'ENTITY_OVERRIDE_MODE_OVERRIDE'

    session_entity_type_name = client.session_entity_type_path(
        project_id, session_id, entity_type_display_name)

    entities = [
        dialogflow.types.EntityType.Entity(value=value, synonyms=[value])
        for value in entity_values]

    session_entity_type = dialogflow.types.SessionEntityType(
        name=session_entity_type_name,
        entity_override_mode=entity_override_mode,
        entities=entities)

    response = client.create_session_entity_type(
        session_path, session_entity_type)

    print('SessionEntityType created: \n\n{}'.format(response))


def _inject_entities():
    import os
    from concurrent.futures import ThreadPoolExecutor
    import dialogflow_v2 as dialogflow

    project_id = os.environ['GOOGLE_CLOUD_PROJECT']
    session_id = 'session123'
    entity_type_names = ['test-entity', 'test-entity-2']

    client = dialogflow.SessionEntityTypesClient()
    session_path = client.session_path(project_id, session_id)

    executor = ThreadPoolExecutor(len(entity_type_names))
    upload_results = {}

    for entity_type_name in entity_type_names:
        upload_results[entity_type_name] = executor.submit(
            create_session_entity_type,
            client,
            session_path,
            entity_type_name,
            project_id,
            session_id)

    for name, res in upload_results.items():
        res.result()

    print('\n\n###### LIST ######')
    session_entity_types = client.list_session_entity_types(session_path)

    for session_entity_type in session_entity_types:
        print(session_entity_type)
```

**Comment by mcikosos** [comment]
> Oh I forgot to ask, about how many session entities are you trying to update?

I try to upload 7 session entities

**Comment by mcikosos** [comment]
I will provide some sample data (entity values) and then could You try with "user" created session ?
I create SE from webhook and use sessionId from request.

**Comment by nnegrey** [comment]
Any updates on this?

**Comment by mcikosos** [comment]
Sorry, we switched to new dialogflow API and stopped creating session entities using this library.
If issue is not reproduced please close it. 
Thank you for your help
