### ISSUE TITLE
Doubts regarding session client

### ISSUE THREAD

**Issue by sid8491** [googleapis/dialogflow-python-client-v2#145]
Hi Team,

I wanted to know the details of session_client object of dialogflow, about its timeout/validity etc.

Suppose I made a session client to call detect_intent() like below:

```
from google.oauth2 import service_account
import dialogflow
SERVICE_ACCOUNT_FILE = 'somepath/somemorepath/df-agent.json'
credentials = service_account.Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE)
project_id = 'my-project-id'
session_client = dialogflow.SessionsClient(credentials=credentials)
```

Now, I will be using this client whenever I get a text request from some customer to call dialogflow.
My doubts are:

- Is there any max number of the request before this client gets destroyed?
- Is there any timeout, like if the client is not used for some time-period then it gets destroyed? (what if the request is coming after 5-7 days, will the client be still active)
- Do we need to validate session_client before calling dialogflow?

I could not find any details regarding these in documentation.
Please advise.

**Comment by sid8491** [comment]
any update?

**Comment by nnegrey** [comment]
The answer should be no to all of those, as gRPC should handle all of that for you behind the scenes. So you should be good to go with the one client.

**Comment by nnegrey** [comment]
Closing but feel free to re-open for more questions. :)
