### ISSUE TITLE
example detect_intent_stream.py giver error 

### ISSUE THREAD

**Issue by yash2607** [googleapis/dialogflow-python-client-v2#146]
![Screenshot from 2019-09-23 22-44-20](https://user-images.githubusercontent.com/39911645/65447651-b1049f00-de54-11e9-8c2a-812a69abd4b8.png)

#### Environment details

  - OS:Ubuntu
  - Python version: 2.7.15
  - pip version:19.2.3
  - `dialogflow` version: V2

Thanks!

**Comment by AlexRoidl** [comment]
Hi, I have the same issue!

**Comment by busunkim96** [comment]
Hi, do either of you know when this began happening?

**Comment by yash2607** [comment]
> Hi, do either of you know when this began happening?
Hello,
I was trying to run this code from past week, but i was unable to stream the audio to dialogue flow. I was getting the same error everytime. I tried it on Raspbean Buster (Raspberry Pi 4 ) still the same error. 

Thankyou

**Comment by nnegrey** [comment]
Have you tried with one of the provided audio files in the `resources` folder?

I tried with the same version of python and pip. 
Is this your dialogflow version? `dialogflow==0.6.0`

**Comment by yash2607** [comment]
> Have you tried with one of the provided audio files in the `resources` folder?
> 
> I tried with the same version of python and pip.
> Is this your dialogflow version? `dialogflow==0.6.0`

Thankyou for the help, Its working fine with the sample audio files from resources but not with the custom recorded files. It seems there was some difference in the audio/file formats i was passing previously.
