### ISSUE TITLE
detect_intent_stream doesn’t show result

### ISSUE THREAD

**Issue by AlexRoidl** [googleapis/dialogflow-python-client-v2#148]
I am running the example code of detect_intent_stream.

The intermediate results seem great, but at the end the whole sentence is empty.
See the screenshot.
I tried different audio files all with the same result.

<img width="466" alt="Screenshot 2019-09-24 at 14 42 43" src="https://user-images.githubusercontent.com/7574167/65512599-d687bc00-ded9-11e9-9773-f093f3ca673c.png">

OS:Mac Mojave
Python version: 3.7.4 
pip version: 19.2.3
dialogflow version: V2

Thanks

**Comment by nnegrey** [comment]
Add a check for `response.recognition_result.is_final`
The response after the `is_final` is sent will include all the content.

Might be something with the audio files.
