### ISSUE TITLE
Get list of confidence values of all intents per utterance

### ISSUE THREAD

**Issue by Navid-callstats-git** [googleapis/dialogflow-python-client-v2#150]
For each utterance, I get only the largest value (or Intent Probability) in "intent_detection_confidence". Is there any way that I receive a list of confidence values for all intents for each inserted utterance?

**Comment by nnegrey** [comment]
No, detectIntent only returns 1 intent.

**Comment by Navid-callstats-git** [comment]
But you can expose all probabilities of intent classes in a list rather than just showing the one with max probability. It would be very useful since one phrase might include multiple intents.
