### ISSUE TITLE
Create an "example" session

### ISSUE THREAD

**Issue by marcosvidolin** [googleapis/dialogflow-python-client-v2#161]
Create an 'example' dir with some core basic client usages.

**Comment by nnegrey** [comment]
Howdy, this is just our client library repo, you can find the samples in either:
1: On GitHub in our sample repo: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/dialogflow/cloud-client

or 

2: on the official docs pages: https://cloud.google.com/dialogflow/docs/
