### ISSUE TITLE
Add environment_session_path method to V2 SessionsClient

### ISSUE THREAD

**Issue by mark-de-haan** [googleapis/dialogflow-python-client-v2#164]
For the last months we have been using the v2_beta version of this library.
We wanted to upgrade to V2 but discovered that the SessionClient.environment_session_path() no longer exists. We used this method to set which environment of our dialogflow model should be used.

```python
# Example
session_client = dialogflow.SessionsClient()
session_path = session_client.environment_session_path(project='project-id', session='session-id', environment='draft' | 'production', user='user-id')
```

Result is is that we can only use draft version of our model.

My feature request is to readd this to the V2 client.

If there is another way of specifying which Dialogflow environment to use please point me to the documentation.

**Comment by busunkim96** [comment]
Hi @mark-de-haan,

If you'd prefer to use the v2, you can construct that `session_path` string. Resource name path helpers will be going away across libraries in the next year anyway.

```python
project = "project-id"
environment = "test-environment"
user = "test-user"
session="test-session"
session_path = f"projects/{project}/agent/environments/{environment}/users/{user}/sessions/{session}"
```

The [generated documentation](https://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2beta1/api.html) specifies the path format. Here is some more general documentation about [resource name paths](https://cloud.google.com/apis/design/resource_names).
