### ISSUE TITLE
Get default response of some entity not intent

### ISSUE THREAD

**Issue by Sadam1195** [googleapis/dialogflow-python-client-v2#181]
Hi everyone,

I was looking for method that returns default response of entity based on entity name. I couldn't find any method in current version of python client library. Does current version has any method for that or does anyone know any way around for that?

-Thanks

@nnegrey @busunkim96

**Comment by nnegrey** [comment]
You can list the entities inside a specific entity type. 
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dialogflow/cloud-client/entity_management.py#L35-L46

**Comment by Sadam1195** [comment]
What is `entity_type_id`?

**Comment by nnegrey** [comment]
Yep, so just to clarify: entity types are basically a bucket, entities are anything you put in that bucket. 
https://cloud.google.com/dialogflow/docs/entities-overview#terminology

The `entity_type_id` is basically the UUID of your entity type bucket. 

You can use this to get your `entity_types`: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dialogflow/cloud-client/entity_type_management.py#L31-L42

**Comment by Sadam1195** [comment]
Okay, thanks for clearing that up. It doesn't answer my question though. 
What I want is to get entity's default value by entity's name, does this repo any method in it. I'm not sure if I can get what I want with just one method. Can you maybe provide a code for method which takes entity's name as input and returns it's default value. 
Thanks

**Comment by nnegrey** [comment]
No, it doesn't as entities on their own aren't unique values and can't be referenced directly. Multiple entities could share the same name.
