### ISSUE TITLE
Docs: Blank page

### ISSUE THREAD

**Issue by linceaerian** [googleapis/dialogflow-python-client-v2#199]
Hello Maintainers,

Is it just me or the RTD is broken ?

#### Environment details

1. Windows & Firefox|Chrome latest

#### Steps to reproduce

1. Go to https://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/types.html?highlight=entities#dialogflow_v2.types.SessionEntityType.entities

2. Check the page, page is blank

![image](https://user-images.githubusercontent.com/1318470/82348746-8f66b200-99f9-11ea-89cf-cb8dd08fa335.png)

3. Check the search at https://dialogflow-python-client-v2.readthedocs.io/en/latest/search.html?q=entities&check_keywords=yes&area=default

4. Click on any result, page is still blank

**Comment by munkhuushmgl** [comment]
As it noted in grey textbox with red border at top of the page, Python2 is no longer supported since Jan 1, 2020.

**Comment by munkhuushmgl** [comment]
@linceaerian Are you looking for this?
https://dialogflow-python-client-v2.readthedocs.io/en/latest/index.html

I would suggest you to use Python 3 DialogFlow if there is no particular reason to Python 2 version.

**Comment by linceaerian** [comment]
Hello @munkhuushmgl 

Nevermind... not sure how I arrived on this link... I'm currently using Python 3... I searched for the doc and found the link you gave just in last message (v2), as show in the screenshot if you browse on "whatever the ref" on the page, it'll display a blank page, ex: 

![image](https://user-images.githubusercontent.com/1318470/83071461-74d1b000-a06d-11ea-843d-9f47e1f8ea09.png)

Give the previous screen like:
![image](https://user-images.githubusercontent.com/1318470/83071507-831fcc00-a06d-11ea-8067-d8cf75032fc9.png)

After your comments I re-reading the Readme and found that the latest & correct link to doc is https://googleapis.dev/python/dialogflow/latest/index.html

Where
![image](https://user-images.githubusercontent.com/1318470/83071420-5f5c8600-a06d-11ea-99e8-695fb8ab9928.png)

Works still fine:
![image](https://user-images.githubusercontent.com/1318470/83071575-a480b800-a06d-11ea-8955-6bc853b12038.png)

So nevermind, :) thanks for your time

**Comment by voron434** [comment]
@munkhuushmgl 
[Link in the OP's post](https://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/types.html?highlight=entities#dialogflow_v2.types.SessionEntityType.entities) is not about Python v2, but about Dialogflow API v2, so link should be alive.

I've got a few blogposts about Dialogflow and all of the links to docs I give to people are broken now :( Changing it every time is really frustrating :(

If you changed the API so `dialogflow_v2.types.SessionEntityType.entities` is no longer exists, please, leave a note where to find new information about same method or add a version name into link path so the users of the old version wouldnt lose their links.
