### ISSUE TITLE
Update Follow Up intent

### ISSUE THREAD

**Issue by Juliopdata** [googleapis/dialogflow-python-client-v2#204]
**Environment details:**
OS type and version: Ubuntu 18.04.4 LTS
Python version and virtual environment information: Python 3.6.9
dialogflow version: Latest

I'm trying to add training phrases to a Follow Up intent. Here is my code:

```
def list_intents(project_id, client, parent):
    intents = client.list_intents(parent)
    dict_intents = {}
    for intent in intents:
        dict_intents[intent.name] = intent.display_name
    return dict_intents


def update_intent(project_id, intent_name, training_phrases_parts):
    client = dialogflow.IntentsClient()
    parent = client.project_agent_path(project_id)
    intent_path = ''
    dict_intents = list_intents(project_id, client, parent)
    for key, value in dict_intents.items():
        if value == intent_name:
            intent_path = key
    intent = client.get_intent(
        intent_path, intent_view=dialogflow.enums.IntentView.INTENT_VIEW_FULL)
    training_phrases = []
    for training_phrases_part in training_phrases_parts:
        part = dialogflow.types.Intent.TrainingPhrase.Part(
            text=training_phrases_part)
        training_phrase = dialogflow.types.Intent.TrainingPhrase(parts=[part])
        training_phrases.append(training_phrase)
    intent.training_phrases.extend(training_phrases)
    response = client.update_intent(intent)
    return 'Updated'
```

But I get this error:

`InvalidArgument: 400 com.google.apps.framework.request.BadRequestException: Read-only field 'root_followup_intent_name' cannot be set.`

This code works fine with regular intents but when I try to update a Follow Up Intent it fails...
Any idea what I should do? Any suggestion?

**Comment by munkhuushmgl** [comment]
@Juliopdata `root_followup_intent_name` the name attribute of the intent is a UUID defined by Dialogflow and cannot be changed.

This stackoverflow answer might solve your problem.
Please take a look, if this helps you to resolve this issue
https://stackoverflow.com/questions/52647517/dialogflow-invalid-argument-error-on-followup-intent-update

**Comment by Juliopdata** [comment]
Hi Mike! Thanks for your response. 

I have read that stackoverflow answer but I not sure if it is the same issue because I don't want to change the intent UUID, and also I don't want to update a training phrase. I want to add new training phrases.
It's strange because I can add training phrases to a NON Folllow-up intent but I can't do it to a Follow-ip intent.

Sorry if I missing something these are my first steps with Dialogflow and thanks again for your help.

**Comment by Juliopdata** [comment]
Hi again! Finally I got it.

You have to add an update_mask:
```
intent.training_phrases.extend(training_phrases)
    update_mask = field_mask_pb2.FieldMask(paths=[intent.display_name, 'training_phrases'])
```
Whole script:

```
def list_intents(project_id, client, parent):
    intents = client.list_intents(parent)

    dict_intents = {}

    for intent in intents:
        dict_intents[intent.name] = intent.display_name

    return dict_intents


def update_intent(project_id, intent_name, training_phrases_parts):
    import dialogflow
    client = dialogflow.IntentsClient()
    parent = client.project_agent_path(project_id)
    intent_path = ''
    dict_intents = list_intents(project_id, client, parent)
    for key, value in dict_intents.items():
        if value == intent_name:
            intent_path = key
    intent = client.get_intent(
        intent_path, intent_view=dialogflow.enums.IntentView.INTENT_VIEW_FULL)
    training_phrases = []
    for training_phrases_part in training_phrases_parts:
        part = dialogflow.types.Intent.TrainingPhrase.Part(
            text=training_phrases_part)
        training_phrase = dialogflow.types.Intent.TrainingPhrase(parts=[part])
        training_phrases.append(training_phrase)
    intent.training_phrases.extend(training_phrases)
    update_mask = field_mask_pb2.FieldMask(paths=[intent.display_name, 'training_phrases'])
    response = client.update_intent(intent, update_mask=update_mask)
    return 'Updated'
```

Thanks again and I hope it will be useful to someone

**Comment by munkhuushmgl** [comment]
@Juliopdata Glad you figured out! Thanks for your contribution.

I make a note of this and eventually add to docs somewhere.
