### ISSUE TITLE
No response from API

### ISSUE THREAD

**Issue by Spoonrad** [googleapis/dialogflow-python-client-v2#24]
Hi,

I am facing a specific issue which I thought you may shed some light on.
I am using Dialogflow to detect intents based on a text query. After setting up, I call:

response = session_client.detect_intent(
            session=session, query_input=query_input)

This works fine locally. However, on my AWS Elastic Beanstalk instance, it either works or the script times out. There is no debug information nor errors.

Do you know what the issue may be?

The code used is directly from:
http://dialogflow-python-client-v2.readthedocs.io/en/latest/?#using-dialogflow

Note that I set my session_id to None because I don't care about tracking sessions currently.

**Comment by Spoonrad** [comment]
It appears that I receive responses eventually, but it tends to take > 1 minute to get a response, which is very long.

**Comment by Fguino** [comment]
Could you solve the problem?

**Comment by JustinBeckwith** [comment]
Thanks!  Please do let us know if you're still having any issues.

**Comment by mclgoerg** [comment]
I have the same issue as @Spoonrad How did you fix those long response times?

**Comment by SPostmus** [comment]
Hi @Spoonrad, I'm also having this issue. How did you fix it? It works fine locally, but once deployed into the cloud, I don't get a response anymore (and no error message as well, just nothing).

**Comment by Spoonrad** [comment]
Hi, I'm sorry, I don't remember well, it's a shame I didn't notice that notification from Frguino, I would have remembered then.

I'm pretty sure I never solved the issue in Beanstalk and ended up using the v1 API, which had not yet been deprecated.

We run things differently now and I have had no issue using v2.

Sorry that I can't be of further help.
