### ISSUE TITLE
detect_intent_texts gives empty list_value

### ISSUE THREAD

**Issue by nitishkrs1987** [googleapis/dialogflow-python-client-v2#25]
"detect_intent_texts" method returns empty list_value in "response.query_result.parameters"

**Comment by babujipa** [comment]
I have seen this happening when the agent is created thru api. You may do one of the two below as a work around:
Option 1. Open the intent that is returning empty parameters and just save the intent once. Agent will start the training and after a few seconds will complete training

Option 2: Make the parameter mandatory (especially if you are creating the intent/agent thru api call) in the Action and Parameter session while creating the intent

**Comment by nnegrey** [comment]
This appears to be answered, if not, please feel free to re-open.

Thanks! :)

**Comment by nmud19** [comment]
> I have seen this happening when the agent is created thru api. You may do one of the two below as a work around:
> Option 1. Open the intent that is returning empty parameters and just save the intent once. Agent will start the training and after a few seconds will complete training
> 
> Option 2: Make the parameter mandatory (especially if you are creating the intent/agent thru api call) in the Action and Parameter session while creating the intent

@babujipa thanks, #1 seems to work. Is there any workaround that can be done through code though ?

**Comment by babujipa** [comment]
Yes. If you are generating the intent thru code , make that parameter mandatory and it will work

**Comment by nmud19** [comment]
@babujipa Could you please give me pointers on how to make parameter mandatory through code, I couldn't find any example.  Do we do it through the intent call itself ? 

This is my intent creation call
`dialogflow_v2.types.Intent(
        display_name=display_name,
        training_phrases=training_phrases,
        messages=[message])`

I see that this has a parameter called "parameters".
`parameters:
        Optional. The collection of parameters associated with the
        intent.`
I tried inserting a dictionary here but it has some protobuf error. Is this the correct direction ?

**Comment by babujipa** [comment]
You may have modify the code below to fit into your program

############################
name = intent.name
myintent = intents_client.get_intent(name,intent_view=dialogflow.enums.IntentView.INTENT_VIEW_FULL)
myintent.Parameter.mandatory = True
lang='en'
response  = intents_client.update_intent(myintent, lang)
###########################
