### ISSUE TITLE
Module 'dialogflow' has no attribute 'SessionsClient'

### ISSUE THREAD

**Issue by samhains** [googleapis/dialogflow-python-client-v2#26]
Using dialogflow-0.1.0

```
import dialogflow

session_client = dialogflow.SessionsClient()
```

Error message:

```
Traceback (most recent call last):
  File "dialogflow.py", line 1, in <module>
    import dialogflow
  File "dialogflow.py", line 3, in <module>
    session_client = dialogflow.SessionsClient()
AttributeError: module 'dialogflow' has no attribute 'SessionsClient'
```

Tested on both Windows 10 and Ubuntu 16.04 (Windows subsystem linux)

**Comment by cesarandreslopez** [comment]
Same issue here.

**Comment by cesarandreslopez** [comment]
@samhains found a way out that it worked for me.

Change 

dialogflow.SessionsClient()

for 

dialogflow_v2.SessionsClient()

And also for any other use of dialogflow.(something) within your code.

**Comment by earthat** [comment]
you must import dialogflow_v2

**Comment by abdi-alasow** [comment]
is not working by import dialogflow_v2
