### ISSUE TITLE
How to read the parameters that a query returns?

### ISSUE THREAD

**Issue by lordrubenbp** [googleapis/dialogflow-python-client-v2#30]
I'm currently programming with the dialogflow library for python, but when I get the list of parameters I get from an attempt, it returns me a Struct object that I don't know how to read.

```
 fields {
  key: "apellido1"
  value {
    string_value: "Baena"
  }
}
fields {
  key: "apellido2"
  value {
    string_value: "P\303\251rez"
  }
}
fields {
  key: "nombre"
  value {
    string_value: "Rub\303\251n"
  }
}
```
the documentation of the dialogflow library is very limited and there are no examples.

The best I can guess is that Struct is from the following route

`google.protobuf.struct_pb2`

Thank you very much for your help

**Comment by ToddMorrill** [comment]
I'm having the same issue.

I'm trying to convert a google.cloud.dialogflow_v2.types.QueryResult object to a simple python dictionary. I've got a fairly large custom payload coming through the `webhook_payload` attribute. Needless to say, when I simply call `dict()` on this object, I'm getting a lot of nested objects. I'm trying to avoid 1) writing a function to extract all the data from these nested objects, and 2) using the REST API.

Thanks for any help in advance.

```
response = session_client.detect_intent(session=session, query_input=query_input)
type(response.query_result.webhook_payload)
# google.cloud.dialogflow_v2.types.Struct

dict(response.query_result.webhook_payload)
# {u'hangouts': fields {
#   key: "cards"
#   value {
#     list_value {
#       values {
#         struct_value {
#           fields {
#             key: "header"
#             value {
#               struct_value {
#                 fields {
#                   key: "imageStyle"
#                   value {
#                     string_value: "IMAGE"
# ...
```

**Comment by Luttik** [comment]
Converting back and forth to json does work. You can also use MessageToDict

```
from google.protobuf.json_format import MessageToDict

query_result = MessageToDict(response.query_result)
```

**Comment by dysnomia** [comment]
You should be able to iterate through a struct_pb2 like a normal dict: https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/well_known_types_test.py#L720.

Please let me know whether that helps.

**Comment by nnegrey** [comment]
This appears to be answered, if not, please feel free to re-open.

Thanks! :)
