### ISSUE TITLE
No proxy support

### ISSUE THREAD

**Issue by ericdiliu** [googleapis/dialogflow-python-client-v2#34]
Can not use proxy settings. Any plans to provide support for proxies?

**Comment by JustinBeckwith** [comment]
@theacodes @tseaver do y'all know if the default request stack in this library support proxies?

**Comment by theacodes** [comment]
Both gRPC and Requests should honor `HTTP_PROXY` and `HTTPS_PROXY` env vars.

**Comment by tseaver** [comment]
@JustinBeckwith Why is this repository off in its own little world?  It should be using the `google.cloud` namespace, be integrated with the rest of our process, etc.

**Comment by JustinBeckwith** [comment]
Great questions :) @crwilcox can help rationalize what's going on here.  We recently inherited the repo.
