### ISSUE TITLE
Illegal Instruction on arm devices

### ISSUE THREAD

**Issue by fedden** [googleapis/dialogflow-python-client-v2#44]
Hey folks! Awesome library - its been working flawlessly on my laptop. 

However, when installing the package through pip on a raspberry pi - `sudo pip3 install dialogflow` - and (presumably) downloading binaries through that, after importing the module I get an `Illegal Instruction` error, and the thread crashes. Typically it would look like this:
```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dialogflow
Illegal instruction
```
Incase it saves you a quick google here is a screenfetch detailing specs of the board I'm using.

```
    .',;:cc;,'.    .,;::c:,,.    pi@raspberrypi
   ,ooolcloooo:  'oooooccloo:    OS: Raspbian 9.4 stretch
   .looooc;;:ol  :oc;;:ooooo'    Kernel: armv6l Linux 4.14.30+
     ;oooooo:      ,ooooooc.     Uptime: 14m
       .,:;'.       .;:;'.       Packages: 515
       .... ..'''''. ....        Shell: 594
     .''.   ..'''''.  ..''.      CPU: ARMv6-compatible rev 7 (v6l) @ 1GHz
     ..  .....    .....  ..      RAM: 37MiB / 433MiB
    .  .'''''''  .''''''.  .    
  .'' .''''''''  .'''''''. ''.  
  '''  '''''''    .''''''  '''  
  .'    ........... ...    .'.  
    ....    ''''''''.   .''.    
    '''''.  ''''''''. .'''''    
     '''''.  .'''''. .'''''.    
      ..''.     .    .''..      
            .'''''''            
             ......       

```

**Comment by fedden** [comment]
After a bit of googling this issue https://github.com/google/aiyprojects-raspbian/issues/177 was found, appearently there is an internal binary at google that does not comply with armv6 processors. It's probably not that but I'll share what I can find as I find it. 

In other news:
```
pi@raspberrypi:~/code $ python3                    
Python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170124] on linux                      
Type "help", "copyright", "credits" or "license" for more information.   
>>>
>>> # Fine.                          
>>> import google.api_core    
>>>     
>>> # Bad.                
>>> import google.api_core.gapic_v1                 
Illegal instruction  
```

**Comment by fedden** [comment]
Also a problem here - looks like one of the real issues here are more than one of the modules imported in `google.api_core`.
```
pi@raspberrypi:~/code $ python3                     
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.api_core.grpc_helpers
Illegal instruction
```

**Comment by crwilcox** [comment]
Hi @fedden. The project for api core is https://github.com/GoogleCloudPlatform/google-cloud-python/issues/new  If you wouldn't mind refiling/linking to an issue over there it can get addressed. Also, please include your package version (`pip freeze`) as it is possible you may have an old version.

Thanks!
