### ISSUE TITLE
Segmentation fault on help(entity)

### ISSUE THREAD

**Issue by gmolau** [googleapis/dialogflow-python-client-v2#45]
Calling `help` on an `EntityType` leads to a `Segmentation fault: 11`. See this iPython session:

```
$ ipython
Python 3.6.4 (default, Jan  6 2018, 11:51:59) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import dialogflow as df

In [2]: client = df.EntityTypesClient()

In [3]: name = client.entity_type_path('<project_id>', '<entity_id>')

In [4]: entity = client.get_entity_type(name)

In [5]: help(entity)
Segmentation fault: 11
$
```

Versions: 
* Python: 3.6.4
* Pip: 9.0.1
* OS: macOS 10.13.4
* Dialogflow SDK: 0.2.0
* Google Cloud SDK: 198.0.0

**Comment by crwilcox** [comment]
This does not repro on a current version of dialogflow (https://pypi.org/project/dialogflow/0.5.1/)

Can you try installing a newer version?

**Comment by gmolau** [comment]
I get the exact same result with v0.5.1.

**Comment by crwilcox** [comment]
Here is a simple repro. This succeeds on 3.7 and fails on 3.6.6

```
import dialogflow
help(dialogflow.types.entity_type_pb2.EntityType)
```

**Comment by crwilcox** [comment]
pip freeze for this failure. Up to date on google-api-core, googleapis-common-protos, grpcio

```
pip freeze
cachetools==2.1.0
certifi==2018.10.15
chardet==3.0.4
dialogflow==0.5.1
google-api-core==1.5.0
google-auth==1.5.1
googleapis-common-protos==1.5.3
grpcio==1.16.0
idna==2.7
protobuf==3.6.1
pyasn1==0.4.4
pyasn1-modules==0.2.2
pytz==2018.6
requests==2.20.0
rsa==4.0
six==1.11.0
urllib3==1.24
```

**Comment by tseaver** [comment]
There is nothing we can do in this repo to work around protocolbuffers/protobuf#2974.
