### ISSUE TITLE
Create Context

### ISSUE THREAD

**Issue by khalilchoudhry** [googleapis/dialogflow-python-client-v2#51]
How to send a dictionary in create_context(). As mentioned in documentation, dict should be of protobuf message. I am unable to create context. Please help.

**Comment by nnegrey** [comment]
Hi,

Here's a sample on [Creating a context](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dialogflow/cloud-client/context_management.py#L53-L68)

Let me know if that helps. :)

**Comment by LakeLobster** [comment]
> Hi,
> 
> Here's a sample on [Creating a context](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/dialogflow/cloud-client/context_management.py#L53-L68)
> 
> Let me know if that helps. :)

Your link is dead.
