### ISSUE TITLE
Intermediate results on using session_client.streaming_detect_intent()

### ISSUE THREAD

**Issue by mukkah** [googleapis/dialogflow-python-client-v2#58]
Hi,

Please, is there a way to get intermediate results on using session_client.streaming_detect_intent()?

I explain. I'd like to pass small recorded files which added (appended) compound an audio input stream.

I noticed that if you don't group the audio chunks in a iterator collection (yield), they will not be handled as an unique stream when calling streaming_detect_intent(), so you need to process the stream until you somehow detects the audio input stopped or something similar and then deliver the iterator collection for detection, which is kind of silly since we could have detected intents prior to the end of the streaming (almost the same effect of recording the audio and then calling detect_intent()).
Is there a way to call it separately and inform it is the same stream for getting intermediate results, thus dynamically decide to stop streaming and process the results?

Thanks a lot!

**Comment by eniasebiomo** [comment]
Having same issue

**Comment by dysnomia** [comment]
> I noticed that if you don't group the audio chunks in a iterator collection (yield), they will not be handled as an unique stream when calling streaming_detect_intent(), so you need to process the stream until you somehow detects the audio input stopped or something similar and then deliver the iterator collection for detection, which is kind of silly since we could have detected intents prior to the end of the streaming (almost the same effect of recording the audio and then calling detect_intent()).

The generator you pass into sessions_client.streaming_detect_intent and the partial Speech recognition responses you get are processed concurrently. That is, you can make the generator dependent on the partial recognition results (http://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/types.html#dialogflow_v2.types.StreamingDetectIntentResponse).

**Stopping:** In particular, you decide when to stop Speech recognition by exiting the generator based on whatever signals you want. If you set `single_utterance` to `True` (http://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/types.html#dialogflow_v2.types.StreamingDetectIntentRequest.single_utterance), we will return a `RECOGNITION_EVENT_END_OF_SINGLE_UTTERANCE` event when we believe a Speech utterance has ended. You should then exit the generator (in fact we ignore further input audio).

**Warning:** As described in http://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/types.html#dialogflow_v2.types.StreamingRecognitionResult you will get exactly one intent result per stream (returning multiple intents wouldn't have an obvious semantic). The main use of `StreamingDetectIntent` is to send audio that is being recorded from a microphone, get partial recognition results and then close the microphone after `RECOGNITION_EVENT_END_OF_SINGLE_UTTERANCE`. There is no significant advantage in using `StreamingDetectIntent` if you have prerecorded audio.

> Is there a way to call it separately and inform it is the same stream for getting intermediate results, thus dynamically decide to stop streaming and process the results?

No, separate streams are fully independent of each other.

Please let me know whether that clarified the use of `StreamingDetectIntent`.

**Comment by nnegrey** [comment]
This appears to be answered, if not, please feel free to re-open.

Thanks! :)
