### ISSUE TITLE
Message type "google.cloud.dialogflow.v2.OriginalDetectIntentRequest" has no field named "version"

### ISSUE THREAD

**Issue by gmolau** [googleapis/dialogflow-python-client-v2#61]
I was trying to parse a Dialogflow webhook request from Actions on Google to a `dialogflow_v2beta1.proto.webhook_pb2.WebhookRequest()`, using the example request given in the official [dialogflow/fulfillment-webhook-json](https://github.com/dialogflow/fulfillment-webhook-json/blob/c92e323bc7df8410e307db0be0ceaa2e67c5f381/requests/v2/ActionsOnGoogle/request.json) repo:

```python
google.protobuf.json_format.ParseDict(request_dict, dialogflow_v2beta1.proto.webhook_pb2.WebhookRequest())
```

This failed with the following error:

```python
ParseError: Failed to parse originalDetectIntentRequest field: Message type "google.cloud.dialogflow.v2beta1.OriginalDetectIntentRequest" has no field named "version".
 Available Fields(except extensions): <MessageFields sequence>
```

Looking at the [`google.cloud.dialogflow.v2.OriginalDetectIntentRequest`](https://github.com/googleapis/googleapis/blob/571ec421ab337d6642dfe9a38f472fefb848d80d/google/cloud/dialogflow/v2/webhook.proto#L103) protobuf definition (and also the [compiled python descriptor](https://github.com/dialogflow/dialogflow-python-client-v2/blob/30ae437d47c42b60cc08e05db243c02d5327fbee/dialogflow_v2/proto/webhook_pb2.py#L262)) it seems that it is indeed missing the `version` field that is included in the request example, i.e. that either the protobuf or the example is wrong.

**Comment by Jeremy-WEI** [comment]
Hi gmolau, 
Thanks for reporting this issue. The version field is actually internal and should not send to the webhook. We will fix it. 
In the meantime, can you set ignore_unknown_fields=true when parsing the WebhookRequest?

**Comment by gmolau** [comment]
Yep that's what I'm doing:) Thanks for fixing it!

**Comment by tseaver** [comment]
AFAICT, this is a bug in the [example data](https://github.com/dialogflow/fulfillment-webhook-json/blob/c92e323bc7df8410e307db0be0ceaa2e67c5f381/requests/v2/ActionsOnGoogle/request.json); there isn't anything we can do to fix it in this repo.

Please reopen with more information if I'm incorrect.
