### ISSUE TITLE
Setting Input context

### ISSUE THREAD

**Issue by Akashutreja** [googleapis/dialogflow-python-client-v2#69]
Hi all,
I am trying to create a followup intent and trying to set its input context. but it is showing me following error.
```
TypeError: ('projects/project_id/agent/intents/25a5f667-c9d5-44b4-83f3-d611869f886c',) has type tuple, but expected one of: bytes, unicode
[27/Jun/2018 10:57:55] "POST /intervention/ HTTP/1.1" 500 16952
```
My code is following:
```
intent = dialogflow.types.Intent(
        #parameters= [parameter],
        display_name=display_name,
        training_phrases=training_phrases,
        messages=message,
        ml_disabled=False,
        root_followup_intent_name=root_followup_intent_name,
        parent_followup_intent_name=parent_followup_intent_name,        
        output_contexts=[
        dialogflow.types.Context(
        name=contexts_client.context_path(project_id, "-",output_context),lifespan_count=1)],
        input_context_names=[input_context_name]
  )
```
And my input_context_name is string as 
**projects/project_id/agent/sessions/-/contexts/question_1_followup**
please help

**Comment by jrash06** [comment]
is projects/project_id/agent/intents/25a5f667-c9d5-44b4-83f3-d611869f886c the id of you root followup intent or parent followup intent? it looks like the some variable intended as a string was actually created as a tuple

Do you have a line like this:
my_str = 'my_str_value',
Note the comma at the end, which forces creating a tuple. This is a very common mistake

**Comment by nnegrey** [comment]
This appears to be answered, if not, please feel free to re-open.

Thanks! :)
