### ISSUE TITLE
Google assistant audio autput

### ISSUE THREAD

**Issue by NicolasLifetouch** [googleapis/dialogflow-python-client-v2#70]
Hi, there is a way to get the assistant response as a google assistant audio output? Now i get only text output. I enalbed the google assistant in the response section of the intent.

**Comment by nnegrey** [comment]
Hi, you can now use [Adding Speech Response to Detect Intent Requests](https://cloud.google.com/dialogflow-enterprise/docs/detect-intent-tts)

Let me know if that helps. :)
