### ISSUE TITLE
Can I create a SessionsClient while explicitly passing a service_account.json?

### ISSUE THREAD

**Issue by m90** [googleapis/dialogflow-python-client-v2#71]
I'd like to create a `dialogflow.SessionsClient` without having to define  `GOOGLE_APPLICATION_CREDENTIALS` (as I'm consuming the package in another library).

Reading [this document](https://cloud.google.com/docs/authentication/production) tells me I should be able to use a method like `from_service_account_json` to instantiate my client, but the library does not seem to expose such method.

I also looked at [`google.auth.credentials`](http://google-auth.readthedocs.io/en/latest/reference/google.auth.credentials.html) in order to pass a`credentials` arg to the constructor, but it looks like it doesn't know how to do this either.

Is there any way of passing the location of a credentials file to the `SessionsClient` constructor? Or could I read the file myself and create an instance of `google.auth.credentials.Credentials` myself?

**Comment by TaeMinPark** [comment]
Yes. you can use like this:

```
from google.oauth2 import service_account
dialogflow_key = json.load(open('<service_account_path.json>'))
credentials = (service_account.Credentials.from_service_account_info(dialogflow_key))
session_client = dialogflow_v2.SessionsClient(credentials=credentials)
```

**Comment by m90** [comment]
@TaeMinPark thanks! I actually ended up doing it quite similarly, but without reading the file myself:

```py
from google.oauth2.service_account import Credentials
credentials = Credentials.from_service_account_file('<service_account_json>')
session_client = dialogflow_v2.SessionsClient(credentials=credentials)
```

**Comment by TaeMinPark** [comment]
Nice! I also have to raise an issue but it seems to DialogFlow team is not reading issues...

**Comment by crwilcox** [comment]
The comment above specifies the correct way to do this https://github.com/googleapis/dialogflow-python-client-v2/issues/71#issuecomment-405501051

**Comment by aaronamelgar** [comment]
How do we do this without storing private key JSON on the repo?
