### ISSUE TITLE
Where is documentation on  query_result instance

### ISSUE THREAD

**Issue by caliph007** [googleapis/dialogflow-python-client-v2#84]
I have received the response as a <class 'google.cloud.dialogflow_v2.types.DetectIntentResponse'>

response.query_result give me another object with the information that I would like to access.
But how do i do that? Is there any documentation for the object?

e.g. How do I access the list of parameters?

**Comment by dysnomia** [comment]
DetectIntentResponse is documented at https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#detectintentresponse.

**Comment by avcwisesa** [comment]
So I'm also having a problem with that, then I tried this a few minutes ago, maybe this could help

```python
#queryResult
response = session_client.detect_intent(session=session, query_input=query_input).query_result
#getting intent
    intent = response.intent
#getting output contexts
output_contexts = response.output_contexts
#getting one of the output contexts
output_contexts[0]
#getting parameters
output_contexts[0].parameters
```

then you can continue accessing the parameters like you do dictionary. I agree the documentation kinda lacks. I'd be grateful if someone could explain abt this better

**Comment by dysnomia** [comment]
Sorry, I should have pointed you to more Python-specific documentation:

* Some of the Python samples partially access query_result, e.g. https://github.com/dialogflow/dialogflow-python-client-v2/blob/master/samples/detect_intent_audio.py#L65.
* The generated Python documentation provides more details about QueryResult: http://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2/types.html#dialogflow_v2.types.QueryResult

But agreed, this is somewhat hard to find and to read. We'll try to find some way to improve this.

Some more general notes:

* The Python objects are generated automatically with protobuf. You can infer the interface from the API using the protobuf guide https://developers.google.com/protocol-buffers/docs/reference/python-generated.
* If you already have an object in Python, `help(response.query_result)` and `dir(response.query_result)` are useful to get more inside into the internals.

**Comment by avallone-google** [comment]
caliph007,

I'd like to make it easier to find the python-specific reference documentation. Can you tell me where you looked for this? Also, are you using the Standard or Enterprise Edition?

**Comment by nnegrey** [comment]
Hi, this appears to be resolved, if not, please feel free to re-open.

Thanks! :)

**Comment by okjuan** [comment]
Yeah I think documentation is still lacking. I basically just figured it out through trial+error using `ipdb`.

**Comment by aardvark82** [comment]
I have struggled with the same issues. Even diving into the documentation, I still find it challenging and time-consuming to find out how to access a simple parameter (e.g. named "Organizations" ) as part of the response - i.e. check if present, if present, get the value.
Could someone provide a simple example here? how do i iterate over parameters, and their fields/key values?
