### ISSUE TITLE
google.api_core.exceptions.InvalidArgument: 400 Current user is null Error

### ISSUE THREAD

**Issue by Akashutreja** [googleapis/dialogflow-python-client-v2#86]
Hi can anyone please tell me when I am creating intent on this following line
 `response = intents_client.create_intent(parent, intent)`

I am getting this error  `google.api_core.exceptions.InvalidArgument: 400 Current user is null Error`
Please if anyone knows about it help me.

Thanks

**Comment by Akashutreja** [comment]
Hi,
Thanks for replying. But if it is because of the missing field then it should always show error when I try to create intent, wherever sometimes it is working and sometimes it doesn't.

**Comment by nnegrey** [comment]
Hi, has this been resolved? 

Have you properly setup your `GOOGLE_APPLICATION_CREDENTIALS` and are you properly creating the `parent`?

Thanks

**Comment by tseaver** [comment]
@nnegrey We need a more detailed code example, including the full traceback, to help diagnose the issue.
