### ISSUE TITLE
Unable to import dialogflow_v2beta1

### ISSUE THREAD

**Issue by gouthamgtm** [googleapis/dialogflow-python-client-v2#88]
$ python --version
Python 2.7.13
$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dialogflow_v2beta1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dialogflow_v2beta1/__init__.py", line 17, in <module>
    from dialogflow_v2beta1 import types
  File "/usr/local/lib/python2.7/dist-packages/dialogflow_v2beta1/types.py", line 21, in <module>
    from dialogflow_v2beta1.proto import agent_pb2
  File "/usr/local/lib/python2.7/dist-packages/dialogflow_v2beta1/proto/agent_pb2.py", line 73, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'
>>>

**Comment by gouthamgtm** [comment]
I am getting this error while using dialogflow version **0.5.0** and **0.5.1** only. I have tried **0.4.0** and I was able to import.uninstall the previous version before installing the lower version

_pip install dialogflow==0.4.0_

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share the code you're using to get this error?

**Comment by tseaver** [comment]
I cannot reproduce in a fresh virtualenv:

```bash
$ python2.7 -m virtualenv /tmp/df-p-c-v2/88
New python executable in /tmp/df-p-c-v2/88/bin/python2.7
Also creating executable in /tmp/df-p-c-v2/88/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/df-p-c-v2/88/bin/pip install --upgrade setuptools pip
...
Requirement already up-to-date: setuptools in /tmp/df-p-c-v2/88/lib/python2.7/site-packages (40.6.2)
Requirement already up-to-date: pip in /tmp/df-p-c-v2/88/lib/python2.7/site-packages (18.1)
$ /tmp/df-p-c-v2/88/bin/pip install dialogflow
...
Successfully installed cachetools-3.0.0 certifi-2018.11.29 chardet-3.0.4 dialogflow-0.5.1 enum34-1.1.6 futures-3.2.0 google-api-core-1.6.0 google-auth-1.6.1 googleapis-common-protos-1.5.5 grpcio-1.17.0 idna-2.7 protobuf-3.6.1 pyasn1-0.4.4 pyasn1-modules-0.2.2 pytz-2018.7 requests-2.20.1 rsa-4.0 six-1.11.0 urllib3-1.24.1
$ /tmp/df-p-c-v2/88/bin/python -c "import dialogflow_v2beta1; print(dialogflow_v2beta1.__path__)"
['/tmp/df-p-c-v2/88/lib/python2.7/site-packages/dialogflow_v2beta1']
```

@gouthamgtm Please feel free to reopen with more information.
