### ISSUE TITLE
How to handle google.api_core.exceptions for intent_management ? 

### ISSUE THREAD

**Issue by Rakin061** [googleapis/dialogflow-python-client-v2#91]
There could be numerous ways to reproduce `google.api_core.exceptions` in this library!

For example, while [creating an intent](https://github.com/dialogflow/dialogflow-python-client-v2/blob/cdb21e624bc0e69518296fa6ef1b5f2746cdcadc/samples/intent_management.py#L63) using the `cerate_intent` method  in **intent_management.py**   there will be an exception if I try to create an intent which already exists. 

### Exception:
> google.api_core.exceptions.FailedPrecondition: 400 Intent with the display_name 'Capital' already exists.

### Here's the full traceback 

> Traceback (most recent call last):
>   File "F:\intent_creation_v2\virt\lib\site-packages\google\api_core\grpc_helpers.py", line 54, in error_remapped_callable
>     return callable_(*args, **kwargs)
>   File "F:\intent_creation_v2\virt\lib\site-packages\grpc\_channel.py", line 514, in __call__
>     return _end_unary_response_blocking(state, call, False, None)
>   File "F:\intent_creation_v2\virt\lib\site-packages\grpc\_channel.py", line 448, in _end_unary_response_blocking
>     raise _Rendezvous(state, None, None, deadline)
> grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
> 	status = StatusCode.FAILED_PRECONDITION
> 	details = "Intent with the display_name 'Capital_ind' already exists."
> 	debug_error_string = "{"created":"@1535975402.919000000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1095,"grpc_message":"Intent with the display_name 'Capital_ind' already exists.","grpc_status":9}"
> >
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "F:/intent_creation_v2/app.py", line 141, in <module>
>     res=create_intent(PROJECT_ID,'Capital_ind',["What is the capital of India","Tell me the capital of India"," Do you know the captial of India"],["Delhi","The capital of India is Delhi"])
>   File "F:/intent_creation_v2/app.py", line 127, in create_intent
>     response = intents_client.create_intent(parent, intent)
>   File "F:\intent_creation_v2\virt\lib\site-packages\dialogflow_v2\gapic\intents_client.py", line 467, in create_intent
>     request, retry=retry, timeout=timeout, metadata=metadata)
>   File "F:\intent_creation_v2\virt\lib\site-packages\google\api_core\gapic_v1\method.py", line 139, in __call__
>     return wrapped_func(*args, **kwargs)
>   File "F:\intent_creation_v2\virt\lib\site-packages\google\api_core\retry.py", line 260, in retry_wrapped_func
>     on_error=on_error,
>   File "F:\intent_creation_v2\virt\lib\site-packages\google\api_core\retry.py", line 177, in retry_target
>     return target()
>   File "F:\intent_creation_v2\virt\lib\site-packages\google\api_core\timeout.py", line 206, in func_with_timeout
>     return func(*args, **kwargs)
>   File "F:\intent_creation_v2\virt\lib\site-packages\google\api_core\grpc_helpers.py", line 56, in error_remapped_callable
>     six.raise_from(exceptions.from_grpc_error(exc), exc)
>   File "<string>", line 3, in raise_from
> google.api_core.exceptions.FailedPrecondition: 400 Intent with the display_name 'Capital_ind' already exists.

I have checked that the [response](https://github.com/dialogflow/dialogflow-python-client-v2/blob/master/samples/intent_management.py#L86) inside the **create_intent** method is invoking these exceptions.

So, how can I handle this kind of exception using try-except block / others to ensure meaningful error messages rather than abnormal termination of the program ??

**Comment by Rakin061** [comment]
Wow!! Thinking something intrinsic to Dialogflow library. Didn't thing that way!!
Many thanks!!

**Comment by AlexSissoko** [comment]
Not that I know of. Sorry!

**Comment by nnegrey** [comment]
Hi,

Another way to avoid this, could be to make a request to list or get your existing intents and ensure that the one you are trying to create doesn't already exist. 

Hope that helps. :)
