### ISSUE TITLE
Make a post request to invoke intent without user communication

### ISSUE THREAD

**Issue by Akashutreja** [googleapis/dialogflow-python-client-v2#94]
Hi,
Is there anyone who knows about invoke an intent by making a post request on dialogflow?
I have integrated my chatbot with facebook but to invoke an intent I need to make a post request with some text so that it got invoked automatically(without user interaction).Is there any way to do this? I know it is possible for the customizable bot (using angular etc.) as defined in this link 
 [(https://dialogflow.com/docs/reference/agent/query)] but having hard time to do with third party like facebook.Please if anyone knows help me out here!
Thanks

**Comment by sachitad** [comment]
Well, you can do that using API.

**Comment by nnegrey** [comment]
There's some docs [here](https://cloud.google.com/dialogflow-enterprise/docs/detect-intent-text#detect-intent-text-protocol) on using `curl`.

The client library may be your best bet though, hope that helps.
