### ISSUE TITLE
batch_update_intents

### ISSUE THREAD

**Issue by mattare2** [googleapis/dialogflow-python-client-v2#97]
Is there any documentation on how to make an IntentBatch object to feed into batch_update_intents?

**Comment by nnegrey** [comment]
Hi, We don't have any specific docs on that, but here is the RPC docs for [IntentBatch](https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#intentbatch).

Let me know if that helps.

**Comment by sid8491** [comment]
it would be :
```
{
    "intents": [
        INTENT_VIEW, 
        INTENT_VIEW,
    ]
}
```

INTENT_VIEW would be :
```
dialogflow.types.Intent(
        display_name=display_name,
        training_phrases=training_phrases_parts,
        action=action,
        messages=[responses],
    )
```
